/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Math;

/**
 *
 * @author aamir7110
 */
public class MagicMath extends javax.swing.JFrame {

    /**
     * Creates new form MagicMath
     */
    public MagicMath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MathTitle = new javax.swing.JLabel();
        largestLabel = new javax.swing.JLabel();
        Largesttxt1 = new javax.swing.JTextField();
        Largesttxt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        LargestAnswer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SmallestTxt1 = new javax.swing.JTextField();
        Smallesttxt2 = new javax.swing.JTextField();
        SmallestButton = new javax.swing.JButton();
        smallestAnswer = new javax.swing.JLabel();
        PowerLbl = new javax.swing.JLabel();
        PowerTxt1 = new javax.swing.JTextField();
        Powertxt2 = new javax.swing.JTextField();
        Powerbtn = new javax.swing.JButton();
        PowerAnswer = new javax.swing.JLabel();
        HypotLbl = new javax.swing.JLabel();
        HypotTxt1 = new javax.swing.JTextField();
        hypotTxt2 = new javax.swing.JTextField();
        hyptoBtn = new javax.swing.JButton();
        HypotAnswer = new javax.swing.JLabel();
        RndDwnLbl = new javax.swing.JLabel();
        RndDwnTxt1 = new javax.swing.JTextField();
        RndDwnBtn = new javax.swing.JButton();
        RndDwnAnswer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RndUpTxt1 = new javax.swing.JTextField();
        RndUpBtn = new javax.swing.JButton();
        RndUpAnswer = new javax.swing.JLabel();
        SqrtLbl = new javax.swing.JLabel();
        SqrtTxt = new javax.swing.JTextField();
        SqrtBtn = new javax.swing.JButton();
        SqrtAnswer = new javax.swing.JLabel();
        RadiansLbl = new javax.swing.JLabel();
        RadiansTxt = new javax.swing.JTextField();
        RadiansBtn = new javax.swing.JButton();
        RadiansAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 103, 242));

        MathTitle.setBackground(new java.awt.Color(0, 0, 0));
        MathTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MathTitle.setForeground(new java.awt.Color(255, 0, 0));
        MathTitle.setText("Magic Math Methods");

        largestLabel.setText("Enter Two Numbers And It Will Display The Largest Of The Two");

        Largesttxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Largesttxt1ActionPerformed(evt);
            }
        });

        Largesttxt2.setText(" ");
        Largesttxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Largesttxt2ActionPerformed(evt);
            }
        });

        jButton1.setText("Largest");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LargestAnswer.setText("...");

        jLabel1.setText("Enter Two Numbers And It Will Display The Smallest Of The Two");

        SmallestTxt1.setText(" ");
        SmallestTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallestTxt1ActionPerformed(evt);
            }
        });

        Smallesttxt2.setText(" ");

        SmallestButton.setText("Smallest");
        SmallestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallestButtonActionPerformed(evt);
            }
        });

        smallestAnswer.setText("...");

        PowerLbl.setText("Enter Two Numbers And The Program Will Display The First Number To THe Power of The Second");

        PowerTxt1.setText(" ");

        Powertxt2.setText(" ");

        Powerbtn.setText("Power");
        Powerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerbtnActionPerformed(evt);
            }
        });

        PowerAnswer.setText("...");

        HypotLbl.setText("Enter Two Numbers And It Will Display The Hypotenuse of The Two");

        HypotTxt1.setText(" ");

        hypotTxt2.setText(" ");

        hyptoBtn.setText("Hypotenuse");
        hyptoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hyptoBtnActionPerformed(evt);
            }
        });

        HypotAnswer.setText("...");

        RndDwnLbl.setText("Enter A Number To Round Down");

        RndDwnTxt1.setText("  ");

        RndDwnBtn.setText("Round Down");
        RndDwnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RndDwnBtnActionPerformed(evt);
            }
        });

        RndDwnAnswer.setText("...");

        jLabel2.setText("Enter A Number To Round Up");

        RndUpTxt1.setText(" ");

        RndUpBtn.setText("Round Up");
        RndUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RndUpBtnActionPerformed(evt);
            }
        });

        RndUpAnswer.setText("...");

        SqrtLbl.setText("Enter A Number To Find Its Square Root");

        SqrtTxt.setText(" ");

        SqrtBtn.setText("Square Root");
        SqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtBtnActionPerformed(evt);
            }
        });

        SqrtAnswer.setText("...");

        RadiansLbl.setText("Enter An Angle in Degrees And It Will Convert To Radians");

        RadiansTxt.setText(" ");

        RadiansBtn.setText("Radians");
        RadiansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiansBtnActionPerformed(evt);
            }
        });

        RadiansAnswer.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(largestLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SmallestTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Smallesttxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SmallestButton)
                        .addGap(113, 113, 113)
                        .addComponent(smallestAnswer))
                    .addComponent(PowerLbl)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HypotTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(hypotTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hyptoBtn)
                                .addGap(91, 91, 91)
                                .addComponent(HypotAnswer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Largesttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Largesttxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(116, 116, 116)
                                .addComponent(LargestAnswer)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RndDwnLbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RndDwnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RndDwnBtn))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(RndDwnAnswer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SqrtLbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RndUpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RndUpBtn)
                                .addGap(18, 18, 18)
                                .addComponent(RndUpAnswer)))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HypotLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadiansLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PowerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Powertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Powerbtn)
                        .addGap(121, 121, 121)
                        .addComponent(PowerAnswer)
                        .addGap(285, 285, 285)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadiansTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadiansBtn)
                                .addGap(39, 39, 39)
                                .addComponent(RadiansAnswer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SqrtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SqrtBtn)
                                .addGap(18, 18, 18)
                                .addComponent(SqrtAnswer)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MathTitle)
                .addGap(311, 311, 311))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largestLabel)
                            .addComponent(RndDwnLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Largesttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Largesttxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(LargestAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RndDwnBtn)
                            .addComponent(RndDwnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RndDwnAnswer))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SmallestTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Smallesttxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SmallestButton)
                            .addComponent(smallestAnswer)
                            .addComponent(RndUpBtn)
                            .addComponent(RndUpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RndUpAnswer))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PowerLbl)
                            .addComponent(SqrtLbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MathTitle)
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PowerAnswer)
                            .addComponent(SqrtBtn)
                            .addComponent(SqrtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SqrtAnswer)
                            .addComponent(Powerbtn)
                            .addComponent(Powertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PowerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HypotLbl)
                    .addComponent(RadiansLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HypotTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypotTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hyptoBtn)
                    .addComponent(HypotAnswer)
                    .addComponent(RadiansTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadiansBtn)
                    .addComponent(RadiansAnswer))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Largesttxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Largesttxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Largesttxt1ActionPerformed

    private void Largesttxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Largesttxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Largesttxt2ActionPerformed

    private void SmallestTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallestTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallestTxt1ActionPerformed

    private void SmallestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallestButtonActionPerformed

        double num1,num2,num3;
        
        num1 = Double.parseDouble(SmallestTxt1.getText());
        num2 = Double.parseDouble(Smallesttxt2.getText());
        num3 = Math.min(num1, num2);
        
        smallestAnswer.setText("Min: "+num3);
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallestButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double num1,num2,num3;
        
        num1 = Double.parseDouble(Largesttxt1.getText());
        num2 = Double.parseDouble(Largesttxt2.getText());
        num3 = Math.max(num1, num2);
        
        
        LargestAnswer.setText("max: "+num3);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PowerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerbtnActionPerformed

        double num1,num2,num3;
        
        num1 = Double.parseDouble(PowerTxt1.getText());
        num2 = Double.parseDouble(Powertxt2.getText());
        num3 = Math.pow(num1, num2);
        
        PowerAnswer.setText(""+num3);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerbtnActionPerformed

    private void hyptoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hyptoBtnActionPerformed

        double num1,num2,num3;
        
        num1 = Double.parseDouble(HypotTxt1.getText());
        num2 = Double.parseDouble(hypotTxt2.getText());
        num3 = Math.hypot(num1, num2);
        
        HypotAnswer.setText("Hypot: "+num3);
        
    }//GEN-LAST:event_hyptoBtnActionPerformed

    private void RndDwnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RndDwnBtnActionPerformed

        double num1,num2;
        
        num1 = Double.parseDouble(RndDwnTxt1.getText());
        num2 = Math.floor(num1);
        
        RndDwnAnswer.setText("Rounded: "+num2);
        
    }//GEN-LAST:event_RndDwnBtnActionPerformed

    private void RndUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RndUpBtnActionPerformed

        double num1,num2;
        
        num1 = Double.parseDouble(RndUpTxt1.getText());
        num2 = Math.ceil(num1);
        
        RndUpAnswer.setText("Rounded: "+num2);
        
    }//GEN-LAST:event_RndUpBtnActionPerformed

    private void SqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtBtnActionPerformed

        double num1,num2;
        
        num1 = Double.parseDouble(SqrtTxt.getText());
        num2 = Math.sqrt(num1);
        
        SqrtAnswer.setText("Root: "+num2);
        

    }//GEN-LAST:event_SqrtBtnActionPerformed

    private void RadiansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiansBtnActionPerformed

        double num1,num2;
        
        num1 = Double.parseDouble(RadiansTxt.getText());
        num2 = Math.toRadians(num1);
        
        RadiansAnswer.setText("Radians: "+num2);
        
    }//GEN-LAST:event_RadiansBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HypotAnswer;
    private javax.swing.JLabel HypotLbl;
    private javax.swing.JTextField HypotTxt1;
    private javax.swing.JLabel LargestAnswer;
    private javax.swing.JTextField Largesttxt1;
    private javax.swing.JTextField Largesttxt2;
    private javax.swing.JLabel MathTitle;
    private javax.swing.JLabel PowerAnswer;
    private javax.swing.JLabel PowerLbl;
    private javax.swing.JTextField PowerTxt1;
    private javax.swing.JButton Powerbtn;
    private javax.swing.JTextField Powertxt2;
    private javax.swing.JLabel RadiansAnswer;
    private javax.swing.JButton RadiansBtn;
    private javax.swing.JLabel RadiansLbl;
    private javax.swing.JTextField RadiansTxt;
    private javax.swing.JLabel RndDwnAnswer;
    private javax.swing.JButton RndDwnBtn;
    private javax.swing.JLabel RndDwnLbl;
    private javax.swing.JTextField RndDwnTxt1;
    private javax.swing.JLabel RndUpAnswer;
    private javax.swing.JButton RndUpBtn;
    private javax.swing.JTextField RndUpTxt1;
    private javax.swing.JButton SmallestButton;
    private javax.swing.JTextField SmallestTxt1;
    private javax.swing.JTextField Smallesttxt2;
    private javax.swing.JLabel SqrtAnswer;
    private javax.swing.JButton SqrtBtn;
    private javax.swing.JLabel SqrtLbl;
    private javax.swing.JTextField SqrtTxt;
    private javax.swing.JTextField hypotTxt2;
    private javax.swing.JButton hyptoBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel largestLabel;
    private javax.swing.JLabel smallestAnswer;
    // End of variables declaration//GEN-END:variables
}
